---
exclude_paths:
  - '**/node_modules/**'
  - 'chat-client/.next/**'
  - '**/dist/**'
  - '**/build/**'
  - 'docs/**'
  - 'chat-backend/migrations/**'
  - 'chat-backend/bun.lock'
  - 'chat-client/bun.lock'

engines:
  biome:
    enabled: true
  eslint:
    enabled: false
  tslint:
    enabled: false
